// apps/web/src/pages/SchedulesPage.tsx
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Play, Plus, Trash2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api, ApiError, type Schedule, type ScheduleInput } from "../lib/api.js";
import { pushToast } from "../lib/toast.js";
import { cn, fmtDateTime } from "../lib/utils.js";
import { Badge, Button, Card, Input, Textarea } from "../components/ui/primitives.js";

function TimingBadge({ schedule }: { schedule: Schedule }) {
  const { t } = useTranslation();
  const label = schedule.cron
    ? `cron ${schedule.cron}${schedule.timezone ? ` (${schedule.timezone})` : ""}`
    : t("schedules.everySec", { s: schedule.intervalSec ?? 0 });
  return <Badge tone="muted">{label}</Badge>;
}

function errText(err: unknown): string {
  return err instanceof ApiError ? err.message : String(err);
}

function ScheduleCard({ schedule }: { schedule: Schedule }) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const invalidate = () => void queryClient.invalidateQueries({ queryKey: ["schedules"] });

  const toggle = useMutation({
    mutationFn: () => api.updateSchedule(schedule.id, { enabled: !schedule.enabled }),
    onSuccess: invalidate,
    onError: (err) => pushToast(errText(err)),
  });
  const run = useMutation({
    mutationFn: () => api.runSchedule(schedule.id),
    onSuccess: (res) => {
      pushToast(t("schedules.ranNow", { status: res.status }), "default");
      invalidate();
    },
    onError: (err) => pushToast(errText(err)),
  });
  const remove = useMutation({
    mutationFn: () => api.deleteSchedule(schedule.id),
    onSuccess: invalidate,
    onError: (err) => pushToast(errText(err)),
  });

  const detail =
    schedule.action === "http"
      ? `${schedule.spec.method ?? "GET"} ${schedule.spec.url ?? ""}${schedule.spec.wake ? ` · ${t("schedules.wakes")}` : ""}`
      : schedule.spec.prompt ?? "";

  return (
    <Card className={cn("space-y-2", !schedule.enabled && "opacity-60")}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-medium">{schedule.name}</span>
        <Badge tone={schedule.action === "http" ? "default" : "success"}>
          {t(`schedules.action.${schedule.action}`)}
        </Badge>
        <TimingBadge schedule={schedule} />
        <div className="ml-auto flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            aria-label={`${t("schedules.runNow")} ${schedule.name}`}
            disabled={run.isPending}
            onClick={() => run.mutate()}
          >
            <Play className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            aria-label={`${t("schedules.delete")} ${schedule.name}`}
            disabled={remove.isPending}
            onClick={() => {
              if (confirm(t("schedules.confirmDelete", { name: schedule.name }))) remove.mutate();
            }}
          >
            <Trash2 className="h-4 w-4 text-danger" />
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={toggle.isPending}
            onClick={() => toggle.mutate()}
          >
            {schedule.enabled ? t("schedules.disable") : t("schedules.enable")}
          </Button>
        </div>
      </div>
      <p className="text-xs break-all whitespace-pre-wrap text-muted">{detail}</p>
      <p className="text-xs text-muted">
        {schedule.enabled && schedule.nextRunAt
          ? t("schedules.nextRun", { time: fmtDateTime(schedule.nextRunAt) })
          : t("schedules.paused")}
        {schedule.lastRunAt &&
          ` · ${t("schedules.lastRun", { time: fmtDateTime(schedule.lastRunAt), status: schedule.lastStatus ?? "" })}`}
      </p>
    </Card>
  );
}

const EMPTY_FORM = {
  name: "",
  action: "prompt" as "prompt" | "http",
  timing: "interval" as "interval" | "cron",
  intervalSec: "3600",
  cron: "",
  timezone: "",
  prompt: "",
  url: "",
  wake: false,
};

function CreateForm({ onDone }: { onDone: () => void }) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [form, setForm] = useState(EMPTY_FORM);
  const set = <K extends keyof typeof EMPTY_FORM>(key: K, value: (typeof EMPTY_FORM)[K]) =>
    setForm((f) => ({ ...f, [key]: value }));

  const create = useMutation({
    mutationFn: (input: ScheduleInput) => api.createSchedule(input),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["schedules"] });
      setForm(EMPTY_FORM);
      onDone();
    },
    onError: (err) => pushToast(errText(err)),
  });

  const submit = () => {
    const input: ScheduleInput = {
      name: form.name,
      action: form.action,
      spec:
        form.action === "prompt"
          ? { prompt: form.prompt }
          : { url: form.url, wake: form.wake },
      ...(form.timing === "cron"
        ? { cron: form.cron, ...(form.timezone ? { timezone: form.timezone } : {}) }
        : { intervalSec: Number(form.intervalSec) }),
    };
    create.mutate(input);
  };

  const Mode = ({
    active,
    label,
    onClick,
  }: {
    active: boolean;
    label: string;
    onClick: () => void;
  }) => (
    <Button variant={active ? "default" : "outline"} size="sm" onClick={onClick}>
      {label}
    </Button>
  );

  return (
    <Card className="space-y-3">
      <Input
        placeholder={t("schedules.form.name")}
        value={form.name}
        onChange={(e) => set("name", e.target.value)}
      />
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs text-muted">{t("schedules.form.actionLabel")}</span>
        <Mode
          active={form.action === "prompt"}
          label={t("schedules.action.prompt")}
          onClick={() => set("action", "prompt")}
        />
        <Mode
          active={form.action === "http"}
          label={t("schedules.action.http")}
          onClick={() => set("action", "http")}
        />
        <span className="ml-3 text-xs text-muted">{t("schedules.form.timingLabel")}</span>
        <Mode
          active={form.timing === "interval"}
          label={t("schedules.form.interval")}
          onClick={() => set("timing", "interval")}
        />
        <Mode
          active={form.timing === "cron"}
          label="cron"
          onClick={() => set("timing", "cron")}
        />
      </div>
      {form.timing === "interval" ? (
        <Input
          type="number"
          min={10}
          placeholder={t("schedules.form.intervalSec")}
          value={form.intervalSec}
          onChange={(e) => set("intervalSec", e.target.value)}
        />
      ) : (
        <div className="flex flex-col gap-2 sm:flex-row">
          <Input
            placeholder={t("schedules.form.cron")}
            value={form.cron}
            onChange={(e) => set("cron", e.target.value)}
          />
          <Input
            className="sm:w-44"
            placeholder={t("schedules.form.timezone")}
            value={form.timezone}
            onChange={(e) => set("timezone", e.target.value)}
          />
        </div>
      )}
      {form.action === "prompt" ? (
        <Textarea
          rows={3}
          placeholder={t("schedules.form.prompt")}
          value={form.prompt}
          onChange={(e) => set("prompt", e.target.value)}
        />
      ) : (
        <div className="space-y-2">
          <Input
            placeholder={t("schedules.form.url")}
            value={form.url}
            onChange={(e) => set("url", e.target.value)}
          />
          <label className="flex items-center gap-2 text-sm text-muted">
            <input
              type="checkbox"
              checked={form.wake}
              onChange={(e) => set("wake", e.target.checked)}
            />
            {t("schedules.form.wake")}
          </label>
        </div>
      )}
      <div className="flex justify-end gap-2">
        <Button variant="outline" size="sm" onClick={onDone}>
          {t("common.cancel")}
        </Button>
        <Button size="sm" disabled={create.isPending} onClick={submit}>
          {t("schedules.form.create")}
        </Button>
      </div>
    </Card>
  );
}

/**
 * The active side of the connector surface: user-defined timers. Web/Feishu/
 * webhook wait for something to arrive — these make the runtime act on its
 * own: poll a URL on a period, or hand the agent a task on a clock.
 */
export function SchedulesPage() {
  const { t } = useTranslation();
  const [creating, setCreating] = useState(false);
  const { data, isLoading } = useQuery({
    queryKey: ["schedules"],
    queryFn: () => api.schedules(),
  });
  const schedules = data?.schedules ?? [];

  return (
    <div className="space-y-3 p-4">
      <div className="flex items-start justify-between gap-3">
        {/* min-w-0 lets the subtitle shrink instead of squeezing the button. */}
        <div className="min-w-0">
          <h1 className="text-lg font-semibold">{t("schedules.title")}</h1>
          <p className="mt-1 text-xs text-muted">{t("schedules.subtitle")}</p>
        </div>
        {!creating && (
          <Button size="sm" onClick={() => setCreating(true)}>
            <Plus className="h-4 w-4" /> {t("schedules.new")}
          </Button>
        )}
      </div>
      {creating && <CreateForm onDone={() => setCreating(false)} />}
      {isLoading && <p className="text-sm text-muted">{t("common.loading")}</p>}
      {!isLoading && schedules.length === 0 && !creating && (
        <p className="pt-8 text-center text-sm text-muted">{t("schedules.empty")}</p>
      )}
      {schedules.map((s) => (
        <ScheduleCard key={s.id} schedule={s} />
      ))}
    </div>
  );
}

// frontend/src/pages/SchedulesPage.svelte
<script lang="ts">
  import { createMutation, createQuery, useQueryClient } from "@tanstack/svelte-query";
  import { Plus } from "@lucide/svelte";
  import { t } from "../i18n/index.js";
  import { api, type ScheduleInput } from "../lib/api.js";
  import { errorText } from "../lib/settings.js";
  import { pushToast } from "../lib/toast.js";
  import Page from "../components/Page.svelte";
  import ScheduleCard from "../components/ScheduleCard.svelte";
  import Button from "../components/ui/Button.svelte";
  import Card from "../components/ui/Card.svelte";
  import Input from "../components/ui/Input.svelte";
  import Textarea from "../components/ui/Textarea.svelte";

  const queryClient = useQueryClient();
  let creating = $state(false);
  let form = $state({
    name: "",
    action: "prompt" as "prompt" | "http",
    timing: "interval" as "interval" | "cron",
    intervalSec: "3600",
    cron: "",
    timezone: "",
    prompt: "",
    url: "",
    wake: false,
  });
  const schedulesQuery = createQuery(() => ({ queryKey: ["schedules"], queryFn: () => api.schedules() }));
  let schedules = $derived(schedulesQuery.data?.schedules ?? []);
  const create = createMutation(() => ({
    mutationFn: (input: ScheduleInput) => api.createSchedule(input),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["schedules"] });
      form = { name: "", action: "prompt", timing: "interval", intervalSec: "3600", cron: "", timezone: "", prompt: "", url: "", wake: false };
      creating = false;
    },
    onError: (error) => pushToast(errorText(error)),
  }));

  function submit(): void {
    const input: ScheduleInput = {
      name: form.name,
      action: form.action,
      spec: form.action === "prompt" ? { prompt: form.prompt } : { url: form.url, wake: form.wake },
      ...(form.timing === "cron" ? { cron: form.cron, ...(form.timezone ? { timezone: form.timezone } : {}) } : { intervalSec: Number(form.intervalSec) }),
    };
    create.mutate(input);
  }
</script>

<Page title={$t("schedules.title")}>
  {#snippet actions()}
    {#if !creating}<Button size="sm" onclick={() => (creating = true)}><Plus size={16} />{$t("schedules.new")}</Button>{/if}
  {/snippet}
  <p class="px-1 text-xs text-muted">{$t("schedules.subtitle")}</p>
  {#if creating}
    <Card class="space-y-3" aria-label={$t("schedules.new")}>
      <Input bind:value={form.name} placeholder={$t("schedules.form.name")} />
      <div class="flex flex-wrap items-center gap-2">
        <span class="text-xs text-muted">{$t("schedules.form.actionLabel")}</span>
        <Button variant={form.action === "prompt" ? "default" : "outline"} size="sm" onclick={() => (form.action = "prompt")}>{$t("schedules.action.prompt")}</Button>
        <Button variant={form.action === "http" ? "default" : "outline"} size="sm" onclick={() => (form.action = "http")}>{$t("schedules.action.http")}</Button>
        <span class="ml-3 text-xs text-muted">{$t("schedules.form.timingLabel")}</span>
        <Button variant={form.timing === "interval" ? "default" : "outline"} size="sm" onclick={() => (form.timing = "interval")}>{$t("schedules.form.interval")}</Button>
        <Button variant={form.timing === "cron" ? "default" : "outline"} size="sm" onclick={() => (form.timing = "cron")}>{$t("schedules.cron")}</Button>
      </div>
      {#if form.timing === "interval"}
        <Input type="number" min={10} bind:value={form.intervalSec} placeholder={$t("schedules.form.intervalSec")} />
      {:else}
        <div class="flex flex-col gap-2 sm:flex-row"><Input bind:value={form.cron} placeholder={$t("schedules.form.cron")} /><Input class="sm:w-44" bind:value={form.timezone} placeholder={$t("schedules.form.timezone")} /></div>
      {/if}
      {#if form.action === "prompt"}
        <Textarea rows={3} bind:value={form.prompt} placeholder={$t("schedules.form.prompt")} />
      {:else}
        <div class="space-y-2"><Input bind:value={form.url} placeholder={$t("schedules.form.url")} /><label class="flex items-center gap-2 text-sm text-muted"><input type="checkbox" bind:checked={form.wake} />{$t("schedules.form.wake")}</label></div>
      {/if}
      <div class="flex justify-end gap-2"><Button variant="outline" size="sm" onclick={() => (creating = false)}>{$t("common.cancel")}</Button><Button size="sm" disabled={create.isPending} onclick={submit}>{$t("schedules.form.create")}</Button></div>
    </Card>
  {/if}
  {#if schedulesQuery.isLoading}
    <p class="flex items-center gap-2 px-1 text-sm text-muted"><span class="h-3 w-3 animate-spin rounded-full border-2 border-muted border-t-transparent"></span>{$t("common.loading")}</p>
  {/if}
  {#if !schedulesQuery.isLoading && schedules.length === 0 && !creating}
    <div class="flex flex-col items-center gap-3 py-16">
      <p class="text-sm text-muted">{$t("schedules.empty")}</p>
      <Button size="sm" variant="outline" onclick={() => (creating = true)}><Plus size={14} />{$t("schedules.new")}</Button>
    </div>
  {/if}
  {#each schedules as schedule (schedule.id)}<ScheduleCard {schedule} />{/each}
</Page>
