// apps/web/src/pages/ItemsPage.svelte
<script lang="ts">
  import { createMutation, createQuery, useQueryClient } from "@tanstack/svelte-query";
  import { Plus } from "@lucide/svelte";
  import { t } from "../i18n/index.js";
  import { api, ApiError } from "../lib/api.js";
  import { matchesItem } from "../lib/search.js";
  import { navigate } from "../lib/router.svelte.js";
  import { pushToast } from "../lib/toast.js";
  import Badge from "../components/ui/Badge.svelte";
  import Button from "../components/ui/Button.svelte";
  import Card from "../components/ui/Card.svelte";
  import Input from "../components/ui/Input.svelte";
  import Textarea from "../components/ui/Textarea.svelte";
  import Time from "../components/Time.svelte";

  const queryClient = useQueryClient();
  let all = $state(false);
  let query = $state("");
  let creating = $state(false);
  let title = $state("");
  let brief = $state("");
  let repo = $state("");

  const itemsQuery = createQuery(() => ({
    queryKey: ["items", all],
    queryFn: () => api.workItems(all),
  }));
  let items = $derived(itemsQuery.data?.items ?? []);
  let running = $derived(new Set(itemsQuery.data?.running ?? []));
  let shown = $derived(query.trim() ? items.filter((item) => matchesItem(item, query)) : items);

  const create = createMutation(() => ({
    mutationFn: () =>
      api.createWorkItem({
        title: title.trim(),
        ...(brief.trim() ? { brief: brief.trim() } : {}),
        ...(repo.trim() ? { repo: repo.trim() } : {}),
      }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["items"] });
      title = "";
      brief = "";
      repo = "";
      creating = false;
    },
    onError: (error) => pushToast(error instanceof ApiError ? error.message : String(error)),
  }));

  function openItem(id: string, event: MouseEvent): void {
    if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    event.preventDefault();
    navigate(`/items/${id}`);
  }
</script>

<div class="space-y-3 p-4">
  <div class="flex items-center justify-between gap-2">
    <h1 class="text-lg font-semibold">{$t("items.title")}</h1>
    <div class="flex shrink-0 items-center gap-2">
      {#if query.trim()}<span class="text-xs text-muted">{$t("items.matched", { n: shown.length, total: items.length })}</span>{/if}
      <Button variant="outline" size="sm" onclick={() => (all = !all)}>{$t(all ? "items.onlyOpen" : "items.showArchived")}</Button>
      {#if !creating}<Button size="sm" onclick={() => (creating = true)}><Plus size={16} />{$t("items.new")}</Button>{/if}
    </div>
  </div>
  {#if creating}
    <Card class="space-y-2">
      <Input autofocus bind:value={title} placeholder={$t("items.form.title")} />
      <Textarea rows={2} bind:value={brief} placeholder={$t("items.form.brief")} />
      <Input bind:value={repo} placeholder={$t("items.form.repo")} />
      <div class="flex justify-end gap-2">
        <Button variant="outline" size="sm" onclick={() => (creating = false)}>{$t("common.cancel")}</Button>
        <Button size="sm" disabled={create.isPending || title.trim().length === 0} onclick={() => create.mutate()}>{$t("items.form.create")}</Button>
      </div>
    </Card>
  {/if}
  <Input bind:value={query} placeholder={$t("items.search")} />
  {#each shown as item (item.id)}
    <a href={`/items/${item.id}`} class="block" onclick={(event) => openItem(item.id, event)}>
      <Card class="transition-colors hover:bg-surface-2">
        <div class="flex items-center justify-between gap-2">
          <div class="min-w-0">
            <div class="font-medium">{item.title}</div>
            <div class="mt-1 text-xs text-muted">{item.id} · {$t("items.updated")} <Time iso={item.updatedAt} /></div>
          </div>
          <div class="flex shrink-0 items-center gap-2">
            {#if running.has(item.id)}
              <Badge tone="default"><span class="mr-1 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-primary"></span>{$t("items.working")}</Badge>
            {/if}
            <Badge tone={item.status === "open" ? "success" : "muted"}>{item.status}</Badge>
          </div>
        </div>
      </Card>
    </a>
  {/each}
  {#if items.length === 0}<p class="pt-8 text-center text-sm text-muted">{$t("items.empty")}</p>{/if}
  {#if items.length > 0 && shown.length === 0}<p class="pt-8 text-center text-sm text-muted">{$t("items.noMatch")}</p>{/if}
</div>

// apps/web/src/pages/ItemsPage.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api, ApiError } from "../lib/api.js";
import { pushToast } from "../lib/toast.js";
import { runningWorkItems } from "../lib/pending.js";
import { matchesItem } from "../lib/search.js";
import { Time } from "../components/Time.js";
import { Badge, Button, Card, Input, Textarea } from "../components/ui/primitives.js";

/** Opening a work item without first talking to the Primary about it. */
function CreateForm({ onDone }: { onDone: () => void }) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [title, setTitle] = useState("");
  const [brief, setBrief] = useState("");
  const [repo, setRepo] = useState("");

  const create = useMutation({
    mutationFn: () =>
      api.createWorkItem({
        title: title.trim(),
        ...(brief.trim() ? { brief: brief.trim() } : {}),
        ...(repo.trim() ? { repo: repo.trim() } : {}),
      }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["items"] });
      onDone();
    },
    onError: (err) => pushToast(err instanceof ApiError ? err.message : String(err)),
  });

  return (
    <Card className="space-y-2">
      <Input
        autoFocus
        placeholder={t("items.form.title")}
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <Textarea
        rows={2}
        placeholder={t("items.form.brief")}
        value={brief}
        onChange={(e) => setBrief(e.target.value)}
      />
      <Input
        placeholder={t("items.form.repo")}
        value={repo}
        onChange={(e) => setRepo(e.target.value)}
      />
      <div className="flex justify-end gap-2">
        <Button variant="outline" size="sm" onClick={onDone}>
          {t("common.cancel")}
        </Button>
        <Button
          size="sm"
          disabled={create.isPending || title.trim().length === 0}
          onClick={() => create.mutate()}
        >
          {t("items.form.create")}
        </Button>
      </div>
    </Card>
  );
}

export function ItemsPage() {
  const { t } = useTranslation();
  const [all, setAll] = useState(false);
  // Items accumulate; scanning a list by eye stops working after a handful.
  const [query, setQuery] = useState("");
  const [creating, setCreating] = useState(false);
  const { data } = useQuery({
    queryKey: ["items", all],
    queryFn: () => api.workItems(all),
  });
  // Which item is busy right now is the first thing you want from a list of
  // them, and the status column cannot say it: "open" covers idle and running.
  const { data: recent } = useQuery({
    queryKey: ["events", "executions"],
    queryFn: () => api.events({ tail: 300 }),
  });
  const running = runningWorkItems(recent?.events ?? []);
  const items = data?.items ?? [];
  const shown = query.trim() ? items.filter((i) => matchesItem(i, query)) : items;

  return (
    <div className="space-y-3 p-4">
      <div className="flex items-center justify-between gap-2">
        <h1 className="text-lg font-semibold">{t("items.title")}</h1>
        <div className="flex shrink-0 items-center gap-2">
          {query.trim() && (
            <span className="text-xs text-muted">
              {t("items.matched", { n: shown.length, total: items.length })}
            </span>
          )}
          <Button variant="outline" size="sm" onClick={() => setAll((v) => !v)}>
            {all ? t("items.onlyOpen") : t("items.showArchived")}
          </Button>
          {!creating && (
            <Button size="sm" onClick={() => setCreating(true)}>
              <Plus className="h-4 w-4" />
              {t("items.new")}
            </Button>
          )}
        </div>
      </div>
      {creating && <CreateForm onDone={() => setCreating(false)} />}
      <Input
        placeholder={t("items.search")}
        value={query}
        onChange={(e) => setQuery(e.target.value)}
      />
      {shown.map((item) => (
        <Link key={item.id} to="/items/$id" params={{ id: item.id }} className="block">
          <Card className="transition-colors hover:bg-surface-2">
            <div className="flex items-center justify-between gap-2">
              <div className="min-w-0">
                <div className="font-medium">{item.title}</div>
                <div className="mt-1 text-xs text-muted">
                  {item.id} · {t("items.updated")} <Time iso={item.updatedAt} />
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                {running.has(item.id) && (
                  <Badge tone="default">
                    <span className="mr-1 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-primary" />
                    {t("items.working")}
                  </Badge>
                )}
                <Badge tone={item.status === "open" ? "success" : "muted"}>{item.status}</Badge>
              </div>
            </div>
          </Card>
        </Link>
      ))}
      {items.length === 0 && (
        <p className="pt-8 text-center text-sm text-muted">{t("items.empty")}</p>
      )}
      {items.length > 0 && shown.length === 0 && (
        <p className="pt-8 text-center text-sm text-muted">{t("items.noMatch")}</p>
      )}
    </div>
  );
}
